### ISSUE TITLE
Only loading on browser when running npm run dev

### ISSUE THREAD

**Issue by gesangseto** [primefaces/sakai-react#44] opened 2023-03-24 03:05 UTC
i just downloaded and installed in js/ts folder with comand
``npm install``
then I run command
``npm run dev``
but when I open it in the browser 127.0.0.1:3000 it just loads without stopping
![image](https://user-images.githubusercontent.com/49031964/227413701-f77f23c4-e2c4-42e9-9e82-e59814bd36be.png)

![image](https://user-images.githubusercontent.com/49031964/227413795-38190135-dc86-4d24-a68d-57cf69ebb195.png)
and I didn't find any errors in the browser console log

**Comment by Yash636261** [comment] 2023-03-26 09:38
i'm getting " This 127.0.0.1 page can’t be found. "
any solution?

**Comment by habubey** [comment] 2023-04-24 11:47
I am unable to reproduce this issue and it appears to be working for us. Therefore, I will be closing this ticket. However, if you continue to experience the error, please open one more ticket.

**Closed by habubey** 2023-04-24 11:47 UTC
